[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["Andy <akfarrington@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
actix-web = "1.0"
serde = "1.0.98"